name: Hello World

on:
  push:
    branches: ["main"]

jobs:
  helloworld:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
      - run: uname -a
      - run: id
      - run: env

